version: '3'

services:
  kafka-ui:
    image: kafka-ui
    container_name: kafka-ui
    volumes:
      - ./data:/data
    ports:
      - 8089:8081
      - 8080:8080
    environment:
      KAFKA_HOST: "kafka.dckr"