version: '3'

services:
  kafka-ui:
    image: mikekonan/kafka-ui:latest
    container_name: kafka-ui
    volumes:
      - ./kafka-ui/rethinkdb_data:/rethinkdb_data
    ports:
      - 3005:3005
    environment:
      KAFKA_HOST: "kafka"